version: "3"

services:
  db:
    image: postgres
    ports:
     - 5433:5432
    volumes:
     - .data_pg:/var/lib/postgresql/data
     - ./docker-init-db.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=newsreader
    networks:
      - shared-net
networks:
  shared-net:
    external: true

